// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"database/sql"
)

type User struct {
	ID       int64
	Email    string
	Username string
	Password string
	Bio      sql.NullString
	Image    sql.NullString
}
