// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :exec
INSERT INTO
    users (email, username, password, bio, image)
VALUES
    (?, ?, ?, ?, ?) RETURNING id
`

type CreateUserParams struct {
	Email    string
	Username string
	Password string
	Bio      sql.NullString
	Image    sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.ExecContext(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Bio,
		arg.Image,
	)
	return err
}
