// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :one
INSERT INTO
    users (email, username, password, bio, image)
VALUES
    (?, ?, ?, ?, ?) RETURNING id
`

type CreateUserParams struct {
	Email    string
	Username string
	Password string
	Bio      sql.NullString
	Image    sql.NullString
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.Email,
		arg.Username,
		arg.Password,
		arg.Bio,
		arg.Image,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
