// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlc

import (
	"context"
)

const getPingMessage = `-- name: GetPingMessage :one
SELECT message FROM pings
LIMIT 1
`

func (q *Queries) GetPingMessage(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getPingMessage)
	var message string
	err := row.Scan(&message)
	return message, err
}
